import './globals.css';
import { Outfit } from 'next/font/google';

import { Footer } from '@/components';

const inter = Outfit({
  subsets: ['latin'],
});

export const metadata = {
  title: 'Mahmoud Elalfy',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        {children}
        <Footer />
      </body>
    </html>
  );
}
